/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-09-28 05:18:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.htepayIndex;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.htdz.eht_portal.global.Config;
import com.htdz.eht_portal.global.Config;
import com.htdz.eht_portal.global.Config;

public final class reg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/tlds/htdz-tags.tld", Long.valueOf(1475039573000L));
    _jspx_dependants.put("/WEB-INF/jsp/include/footer.jsp", Long.valueOf(1475039576000L));
    _jspx_dependants.put("/WEB-INF/tlds/htdz-functions.tld", Long.valueOf(1475039573000L));
    _jspx_dependants.put("/WEB-INF/jsp/include/taglibs.jsp", Long.valueOf(1475039576000L));
    _jspx_dependants.put("/WEB-INF/jsp/include/reg-header.jsp", Long.valueOf(1475039576000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftag_005ftoken_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftag_005ftoken_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ftag_005ftoken_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("main");
      // /WEB-INF/jsp/include/taglibs.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(Config.getParam("main") );
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("resource");
      // /WEB-INF/jsp/include/taglibs.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(Config.getParam("resource") );
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("upload");
      // /WEB-INF/jsp/include/taglibs.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(Config.getParam("upload") );
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("merMain");
      // /WEB-INF/jsp/include/taglibs.jsp(10,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(Config.getParam("merMain") );
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f4.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setVar("qfbMain");
      // /WEB-INF/jsp/include/taglibs.jsp(11,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setValue(Config.getParam("qfbMain") );
      int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
      if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      out.write("\r\n");
      out.write("\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f5 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f5.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f5.setVar("sessionUser");
      // /WEB-INF/jsp/include/taglibs.jsp(13,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f5.setValue(request.getSession().getAttribute(com.htdz.eht_portal.global.Constants.SESSION_USER));
      int _jspx_eval_c_005fset_005f5 = _jspx_th_c_005fset_005f5.doStartTag();
      if (_jspx_th_c_005fset_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f5);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f5);
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>会员注册-航天支付平台</title>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/common.css\"></link>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/index.css\"></link>\r\n");
      out.write("\r\n");
      out.write("\t<!--适用于ie6及以下-->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/ie6.css\" />\r\n");
      out.write("\r\n");
      out.write("\t<!--使用于ie7-->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/ie7.css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery-1.7.2.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/common.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tvar nick_str_regex = /^[a-zA-Z0-9]{3,8}$/;\r\n");
      out.write("\t\t\tvar nick_cn_regex = /^[\\u4e00-\\u9fa5]{2,5}$/;\r\n");
      out.write("\t\t\tvar reg_passwd_regex = /^[a-zA-Z0-9~@#$&*_+.?]{8,18}$/;\r\n");
      out.write("\t\t\t//var passwd_regex_num = /^\\d{8,18}$/g; //纯数字\r\n");
      out.write("\t\t\t//var passwd_regex_eng = /^[a-zA-z]{8,18}$/g; //纯字母\r\n");
      out.write("\t\t\t//var passwd_regex_other = /^[^0-9a-zA-Z]{8,18}$/g; //纯特殊字符\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction subCheck() {\r\n");
      out.write("\t\t\t\tvar username = $(\"#userName\").val();\r\n");
      out.write("\t\t\t\tvar nickname = $(\"#nickName\").val();\r\n");
      out.write("\t\t\t\tvar passwd = $(\"#passwd\").val();\r\n");
      out.write("\t\t\t\tvar passwdConfirm = $(\"#passwdConfirm\").val();\r\n");
      out.write("\t\t\t\tvar kaptcha = $(\"#kaptcha\").val();\r\n");
      out.write("\t\t\t\tif (ajaxValidUserName(username) && validNickName(nickname)&& validPasswd(passwd) && validPasswdConfirm(passwdConfirm)&& ajaxValidCheckCode(kaptcha)) {\r\n");
      out.write("\t\t\t\t\t$(\"#regForm\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction ajaxValidUserName(val) {\r\n");
      out.write("\t\t\t\tif (val == \"\") {\r\n");
      out.write("\t\t\t\t\t$(\"#userNameMsg\").html(\"用户名不能为空!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if (!phone_regex.test(val) && !email_regex.test(val)) {\r\n");
      out.write("\t\t\t\t\t$(\"#userNameMsg\").html(\"用户名为手机号码或邮箱地址!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#userNameMsg\").html(\"\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar has = \"1\";\r\n");
      out.write("\t\t\t\t$.ajax( {\r\n");
      out.write("\t\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\"userName\" : val\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajaxValidUserName.do\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\thas = data;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tif (has == \"1\") {\r\n");
      out.write("\t\t\t\t\t$(\"#userNameMsg\").html(\"该用户名已经存在!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t//$(\"#userNameMsg\").html(\"该用户名可以使用!\");\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction validNickName(val) {\r\n");
      out.write("\t\t\t\tif (val == \"\") {\r\n");
      out.write("\t\t\t\t\t$(\"#nickNameMsg\").html(\"昵称不能为空!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#nickNameMsg\").html(\"\");\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction containTwoType(val){\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction validPasswd(val) {\r\n");
      out.write("\t\t\t   // var b1 = passwd_regex_num.test(val);\r\n");
      out.write("\t\t\t //   var b2 = passwd_regex_eng.test(val);\r\n");
      out.write("\t\t\t  //  var b3 = passwd_regex_other.test(val);\r\n");
      out.write("\t\t\t  //  passwd_regex_num.lastIndex = 0;\r\n");
      out.write("\t\t\t  //  passwd_regex_eng.lastIndex = 0;\r\n");
      out.write("\t\t\t  //  passwd_regex_other.lastIndex = 0;\r\n");
      out.write("\t\t\t  //  alert(b1+\"||\"+b2+\"||\"+b3);\r\n");
      out.write("\t\t\t  var passwd = /^(?!\\d+$)(?![a-zA-Z]+$)(?![^\\da-zA-Z]+$).{8,20}$/ ;\r\n");
      out.write("\t\t\t\tif (val == \"\") {\r\n");
      out.write("\t\t\t\t\t$(\"#passwdMsg\").html(\"密码不能为空!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if (!passwd.test(val)) {\r\n");
      out.write("\t\t\t\t\t$(\"#passwdMsg\").html(\"由8位以上的字符组成（至少包括英文、数字和特殊字符中的2种）!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#passwdMsg\").html(\"\");\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction validPasswdConfirm(val) {\r\n");
      out.write("\t\t\t\tif (val != $(\"#passwd\").val()) {\r\n");
      out.write("\t\t\t\t\t$(\"#passwdConfirmMsg\").html(\"确认密码和密码输入不一致!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#passwdConfirmMsg\").html(\"\");\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction ajaxValidCheckCode(val) {\r\n");
      out.write("\t\t\t\tif (val == \"\") {\r\n");
      out.write("\t\t\t\t\t$(\"#kaptchaMsg\").html(\"请输入验证码!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if (!kaptcha_regex.test(val)) {\r\n");
      out.write("\t\t\t\t\t$(\"#kaptchaMsg\").html(\"你输入的验证码格式不正确!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#kaptchaMsg\").html(\"\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar has = \"0\";\r\n");
      out.write("\t\t\t\t$.ajax( {\r\n");
      out.write("\t\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajaxValidImg.do?kaptcha=\" + val,\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\thas = data;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tif (has == \"0\") {\r\n");
      out.write("\t\t\t\t\t$(\"#kaptchaMsg\").html(\"你输入的验证码有误!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#kaptchaMsg\").html(\"\");\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction changeKaptchaImg() {\r\n");
      out.write("\t\t\t\t$(\"#kaptchaImg\").attr('src','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Kaptcha.jpg?' + Math.floor(Math.random() * 100));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t function getResult(s){\r\n");
      out.write("\t\t\t\t\t\t  if(s.length < 8){\r\n");
      out.write("\t\t\t\t\t\t   return 0;\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t  var ls = 0;\r\n");
      out.write("\t\t\t\t\t\t  if (s.match(/[0-9]/ig)||s.match(/[a-z]/ig)){\r\n");
      out.write("\t\t\t\t\t\t   ls = 1;\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t  if (s.match(/[a-z]/ig)&&s.match(/[0-9]/ig)){\r\n");
      out.write("\t\t\t\t\t\t   ls = 2;\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t  if (s.match(/(.[^a-zA-Z0-9])/ig)&&s.match(/[a-z]/ig)&&s.match(/[0-9]/ig)){\r\n");
      out.write("\t\t\t\t\t\t   ls = 3;\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t  if (s.length < 8 && ls > 0){\r\n");
      out.write("\t\t\t\t\t\t  \tls =0;\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t  return ls\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t function onPwd(val){\r\n");
      out.write("\t\t\t\t\tvar result= getResult(val)\r\n");
      out.write("\t\t\t\t\tif(result==1){\r\n");
      out.write("\t\t\t\t\t  $(\"#ruo\").addClass(\"grade03\");\r\n");
      out.write("\t\t\t\t\t  $(\"#zhong\").removeClass(\"grade03\");\r\n");
      out.write("\t\t\t\t\t  $(\"#qiang\").removeClass(\"grade03\");\r\n");
      out.write("\t\t\t\t\t}else if(result==2){\r\n");
      out.write("\t\t\t\t\t  $(\"#ruo\").removeClass(\"grade03\");\r\n");
      out.write("\t\t\t\t\t  $(\"#zhong\").addClass(\"grade03\");\r\n");
      out.write("\t\t\t\t\t  $(\"#qiang\").removeClass(\"grade03\");\r\n");
      out.write("\t\t\t\t\t}else if(result>=3){\r\n");
      out.write("\t\t\t\t\t  $(\"#ruo\").removeClass(\"grade03\");\r\n");
      out.write("\t\t\t\t\t  $(\"#zhong\").removeClass(\"grade03\");\r\n");
      out.write("\t\t\t\t\t  $(\"#qiang\").addClass(\"grade03\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t $(\"#ruo\").removeClass(\"grade03\");\r\n");
      out.write("\t\t\t\t\t $(\"#zhong\").removeClass(\"grade03\");\r\n");
      out.write("\t\t\t\t\t $(\"#qiang\").removeClass(\"grade03\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body class=\"reg_body\">\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f6 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f6.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f6.setVar("main");
      // /WEB-INF/jsp/include/taglibs.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f6.setValue(Config.getParam("main") );
      int _jspx_eval_c_005fset_005f6 = _jspx_th_c_005fset_005f6.doStartTag();
      if (_jspx_th_c_005fset_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f6);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f6);
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f7 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f7.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f7.setVar("resource");
      // /WEB-INF/jsp/include/taglibs.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f7.setValue(Config.getParam("resource") );
      int _jspx_eval_c_005fset_005f7 = _jspx_th_c_005fset_005f7.doStartTag();
      if (_jspx_th_c_005fset_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f7);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f7);
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f8 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f8.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f8.setVar("upload");
      // /WEB-INF/jsp/include/taglibs.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f8.setValue(Config.getParam("upload") );
      int _jspx_eval_c_005fset_005f8 = _jspx_th_c_005fset_005f8.doStartTag();
      if (_jspx_th_c_005fset_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f8);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f8);
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f9 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f9.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f9.setVar("merMain");
      // /WEB-INF/jsp/include/taglibs.jsp(10,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f9.setValue(Config.getParam("merMain") );
      int _jspx_eval_c_005fset_005f9 = _jspx_th_c_005fset_005f9.doStartTag();
      if (_jspx_th_c_005fset_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f9);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f9);
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f10 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f10.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f10.setVar("qfbMain");
      // /WEB-INF/jsp/include/taglibs.jsp(11,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f10.setValue(Config.getParam("qfbMain") );
      int _jspx_eval_c_005fset_005f10 = _jspx_th_c_005fset_005f10.doStartTag();
      if (_jspx_th_c_005fset_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f10);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f10);
      out.write("\r\n");
      out.write("\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f11 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f11.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f11.setVar("sessionUser");
      // /WEB-INF/jsp/include/taglibs.jsp(13,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f11.setValue(request.getSession().getAttribute(com.htdz.eht_portal.global.Constants.SESSION_USER));
      int _jspx_eval_c_005fset_005f11 = _jspx_th_c_005fset_005f11.doStartTag();
      if (_jspx_th_c_005fset_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f11);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f11);
      out.write("\r\n");
      out.write("<div id=\"reg-header\">\r\n");
      out.write("    \t<div class=\"h-content\">\r\n");
      out.write("    \t\t<a class=\"logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/eIndex.do\"></a>\r\n");
      out.write("    \t\t<a class=\"old\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/toLinkOld.do\"></a>\r\n");
      out.write("    \t\t<div class=\"h-right\">\r\n");
      out.write("    \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/toLogin.do\">登录</a>\r\n");
      out.write("    \t\t\t<a href=\"javascript:void(0);\" style=\"cursor:default;\">|</a>\r\n");
      out.write("    \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/mobile.do\">手机版</a>\r\n");
      out.write("    \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/safety.do\">安全中心</a>\r\n");
      out.write("    \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/help.do\">帮助中心</a>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("\t<form id=\"regForm\" name=\"regForm\" action=\"regDoValidSub.do\" method=\"post\">\r\n");
      out.write("\t\t");
      if (_jspx_meth_tag_005ftoken_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<div class=\"register\">\r\n");
      out.write("\t\t\t<div class=\"step\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/index/user01.gif\" />\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/index/step01.gif\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sh-layout-two\">\r\n");
      out.write("\t\t\t\t<div class=\"top\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"sd-form-list\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t<legend class=\"pl60\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t设置会员名（电子邮箱或手机号码）\r\n");
      out.write("\t\t\t\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"sd-form-label\" for=\"username\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t*&nbsp;会员名：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"collection\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"userName\" name=\"userName\" maxlength=\"32\" onblur=\"ajaxValidUserName(this.value)\"  class=\"sd-form-txt\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"userNameMsg\" class=\"linkorange\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userNameMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"sd-form-label\" for=\"nickname\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t*&nbsp;昵称：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"collection\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"nickName\" name=\"nickName\" maxlength=\"10\"  onblur=\"validNickName(this.value)\" class=\"sd-form-txt\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"nickNameMsg\" class=\"linkorange\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t<legend class=\"pl60\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t设置登录密码\r\n");
      out.write("\t\t\t\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"sd-form-label\" for=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"vertical-align: top; margin-top: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t*&nbsp;登录密码：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"collection\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"passwd\" name=\"passwd\" maxlength=\"18\" onkeyup=\"onPwd(this.value)\" onblur=\"validPasswd(this.value)\" class=\"sd-form-txt\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"passwdMsg\" class=\"linkorange\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write("</dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <dd id=\"ruo\" class=\"grade02\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t弱\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd id=\"zhong\" class=\"grade02\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t中\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<dd id=\"qiang\" class=\"grade02 \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t强\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"sd-form-label\" for=\"wordsure\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t*&nbsp;确认密码：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"collection\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"passwdConfirm\" name=\"passwdConfirm\" type=\"password\" maxlength=\"18\"  onblur=\"validPasswdConfirm(this.value)\" class=\"sd-form-txt\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"passwdConfirmMsg\" class=\"linkorange\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"sd-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t*&nbsp;验证码：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"collection\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"kaptcha\" name=\"kaptcha\" onblur=\"ajaxValidCheckCode(this.value)\" maxlength=\"4\" class=\"sd-form-code\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Kaptcha.jpg\" id=\"kaptchaImg\" onclick=\"changeKaptchaImg()\"  style=\"vertical-align:middle;width:80px;height:30px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"testtxt\"><a href=\"javascript:changeKaptchaImg()\">看不清，换一张</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"kaptchaMsg\" class=\"linkorange\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kaptchaMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"bottom\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"sd-form-btn pl150 mt10 mb20\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:subCheck()\" class=\"buttonsure ml40\">\r\n");
      out.write("\t\t\t\t\t\t同意协议，注册\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"margin:0px auto;\">\r\n");
      out.write("\t\t\t\t  <textarea rows=\"8\" cols=\"120\" readonly=\"readonly\" style=\"line-height:25px;text-indent:30px;width:100%;\">通过航天易卡网站(www.ehangtian.com)提供的所有服务系浙江航天电子信息产业有限公司（以下称\"本公司\"）所提供之增值服务（以下称\"本服务\"）。\r\n");
      out.write("\t\t    为了保障您的权益，请于注册或使用本服务前，详细阅读本协议所有内容。当您注册或使用本服务时，即表示您已阅读、了解并同意接受本协议之所有内容。我们保留随时修改本协议之权利，并随时通过航天易卡网站公布最新之变更事项，而无需另作个别通知。\r\n");
      out.write("\t\t    1、您了解www.ehangtian.com是提供网络商务服务的网站，非银行或金融机构，所提供之服务不属于银行业务。本公司会妥善保管您的账户上的资金，且这些资金仅供交易使用，不产生利息。无论在任何时候，均会将您的资金独立于本公司资金之外，并不会将您的资金用于非您指示的用途上。\r\n");
      out.write("\t\t    2、当用户注册航天易卡会员时，建议用户提供真实、准确的个人资料，并在个人资料有所变动时进行及时更新。本公司收集个人信息的目的是为用户提供尽可能多的个性化服务以及通告产品优惠信息等的方便。但本公司允许用户保留匿名注册的权利。\r\n");
      out.write("\t\t    3、您同意本公司使用电子方式与您保持联系。电子方式包括发送电子邮件、短信等。本公司承诺不发送与航天易卡无关的内容。\r\n");
      out.write("\t\t    4、为保障航天易卡用户的权益，航天易卡系统将为用户保留第一次注册时登记的邮箱，万一用户账号密码被盗或资料被篡改时，您可以使用您第一次注册时登记的邮箱取回新的密码。因此请用户不要接受他人转让的航天易卡（IC卡），以免纠纷。\r\n");
      out.write("\t\t    5、航天易卡承诺不公开用户的姓名、地址、电子邮箱等个人信息。以下情况除外：\r\n");
      out.write("\t\t       1)经用户授权；\r\n");
      out.write("\t\t       2)相应的法律及程序要求航天电子公司提供用户的个人资料。\r\n");
      out.write("\t\t    6、用户一旦注册成功，将得到一个密码和账号，同时获得航天易卡系统为您提供的虚拟空间，只有将会员与航天易卡的卡号成功绑定才成为航天易卡的合法用户，可正常使用虚拟空间所提供的一切服务和功能。\r\n");
      out.write("\t\t    7、航天易卡的会员用户有义务保证密码和账号的安全，并对利用该密码和账号所进行的一切活动负全部责任；由此所衍生的任何损失或损害，本公司无法也不负担任何责任。用户可以选用本公司提供的安全手段加强账户在使用时的安全性。用户如发现您的密码和账号遭到未授权的使用，或账务记录有错误，或发生其他任何安全问题，有义务立即通知本公司，以减少或挽回损失。\r\n");
      out.write("\t\t    8、用户使用航天易卡服务时必须遵守相关法律法规的有关规定，不得将航天易卡账户用于非法用途；不得干扰和影响航天易卡网络及业务的正常运作，如通过黑客工具、机器人程序等扰乱航天易卡网络及业务的正常运作等；不得利用航天易卡系统的漏洞获取不正当利益；不得做出任何损害航天易卡和其他用户利益的行为。若用户的行为有违本条服务条款，本公司有权视情节轻重采取相应处理措施，以维护航天易卡系统的正常运行以及其他用户的合法权益；由此导致的用户损失本公司不承担任何责任。对情节严重的，本公司保留诉诸法律的权利。\r\n");
      out.write("\t\t    9、当您使用航天易卡服务时，本公司会根据您的消费实际向您提供额外的增值会员服务，各项服务情况详见航天易卡网站公布的有关说明。本公司拥有制定和调整所提供的增值服务之权利。\r\n");
      out.write("\t\t    10、本公司不提供直接的退款服务，用户可通过消费网点的退货或取消交易来处理卡账户余额。\r\n");
      out.write("\t\t    11、对于连续3个月不曾使用且剩余金额为零的航天易卡，本公司有权对该卡号进行冻结处理；对于连续6个月不曾使用且剩余金额为零的航天易卡，本公司有权对该用户卡号进行销户处理。被销户后，原卡号上的所有信息将全部丢失。原卡号用户如需再使用航天易卡服务，请重新绑定新卡号。本公司有权将被销户后的卡号转给其他新用户使用。\r\n");
      out.write("\t\t    12、对于那些在一年内未有任何记录的空会员账号，本公司有权予以消号处理；用户再次使用时，可以重新注册新会员账号。\r\n");
      out.write("\t\t本“用户协议”的各项条款与国家有关法律保持一致，如与法律条款有相抵触的内容，以法律条款为准。</textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f12 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f12.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f12.setVar("main");
      // /WEB-INF/jsp/include/taglibs.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f12.setValue(Config.getParam("main") );
      int _jspx_eval_c_005fset_005f12 = _jspx_th_c_005fset_005f12.doStartTag();
      if (_jspx_th_c_005fset_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f12);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f12);
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f13 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f13.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f13.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f13.setVar("resource");
      // /WEB-INF/jsp/include/taglibs.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f13.setValue(Config.getParam("resource") );
      int _jspx_eval_c_005fset_005f13 = _jspx_th_c_005fset_005f13.doStartTag();
      if (_jspx_th_c_005fset_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f13);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f13);
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f14 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f14.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f14.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f14.setVar("upload");
      // /WEB-INF/jsp/include/taglibs.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f14.setValue(Config.getParam("upload") );
      int _jspx_eval_c_005fset_005f14 = _jspx_th_c_005fset_005f14.doStartTag();
      if (_jspx_th_c_005fset_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f14);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f14);
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f15 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f15.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f15.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f15.setVar("merMain");
      // /WEB-INF/jsp/include/taglibs.jsp(10,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f15.setValue(Config.getParam("merMain") );
      int _jspx_eval_c_005fset_005f15 = _jspx_th_c_005fset_005f15.doStartTag();
      if (_jspx_th_c_005fset_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f15);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f15);
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f16 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f16.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f16.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f16.setVar("qfbMain");
      // /WEB-INF/jsp/include/taglibs.jsp(11,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f16.setValue(Config.getParam("qfbMain") );
      int _jspx_eval_c_005fset_005f16 = _jspx_th_c_005fset_005f16.doStartTag();
      if (_jspx_th_c_005fset_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f16);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f16);
      out.write("\r\n");
      out.write("\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f17 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f17.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f17.setParent(null);
      // /WEB-INF/jsp/include/taglibs.jsp(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f17.setVar("sessionUser");
      // /WEB-INF/jsp/include/taglibs.jsp(13,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f17.setValue(request.getSession().getAttribute(com.htdz.eht_portal.global.Constants.SESSION_USER));
      int _jspx_eval_c_005fset_005f17 = _jspx_th_c_005fset_005f17.doStartTag();
      if (_jspx_th_c_005fset_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f17);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f17);
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("   \t<ul class=\"links\">\r\n");
      out.write("   \t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/help/yksyzc.do\">航天易卡须知</a></li>\r\n");
      out.write("   \t\t<li><a href=\"javascript:alert('乾付宝功能将于近期内推出，尽请期待');\">乾付宝须知</a></li>\r\n");
      out.write("   \t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/help/zczn.do\">新手上路</a></li>\r\n");
      out.write("   \t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/help/htzfjj.do\">关于航天支付</a></li>\r\n");
      out.write("   \t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/help/lxfs.do\">联系我们</a></li>\r\n");
      out.write("   \t</ul>\r\n");
      out.write("   \t<p class=\"coop\">\r\n");
      out.write("   \t\t<label class=\"coop_t\">合作伙伴：</label>\r\n");
      out.write("   \t\t<a href=\"javascript:void(0);\">中国工商银行</a>\r\n");
      out.write("   \t\t<a href=\"javascript:void(0);\">中国农业银行</a>\r\n");
      out.write("   \t\t<a href=\"javascript:void(0);\">中国建设银行</a>\r\n");
      out.write("   \t\t<a href=\"javascript:void(0);\">招商银行</a>\r\n");
      out.write("   \t\t<a href=\"javascript:void(0);\">银联存储</a>\r\n");
      out.write("   \t\t<a href=\"javascript:void(0);\">华润万家</a>\r\n");
      out.write("   \t\t<a href=\"javascript:void(0);\">欧尚超市</a>\r\n");
      out.write("   \t\t<a href=\"javascript:void(0);\">名人名家</a>\r\n");
      out.write("   \t\t<a href=\"javascript:void(0);\">里卡通</a>\r\n");
      out.write("   \t\t<a href=\"javascript:void(0);\">百付宝</a>\r\n");
      out.write("   \t</p>\r\n");
      out.write("   \t<p class=\"bq\">浙ICP备 09037231号-2    浙江航天电子信息产业有限公司  © 2008-2011 All Rights Reserved </p>\r\n");
      out.write("   \t<p class=\"xkz\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/xukezheng.jsp\"  target=\"_black\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/common/xukezheng.jpg\"/></a></p>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tag_005ftoken_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:token
    com.htdz.eht_portal.security.TokenTag _jspx_th_tag_005ftoken_005f0 = (com.htdz.eht_portal.security.TokenTag) _005fjspx_005ftagPool_005ftag_005ftoken_005fnobody.get(com.htdz.eht_portal.security.TokenTag.class);
    _jspx_th_tag_005ftoken_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tag_005ftoken_005f0.setParent(null);
    int _jspx_eval_tag_005ftoken_005f0 = _jspx_th_tag_005ftoken_005f0.doStartTag();
    if (_jspx_th_tag_005ftoken_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftag_005ftoken_005fnobody.reuse(_jspx_th_tag_005ftoken_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ftag_005ftoken_005fnobody.reuse(_jspx_th_tag_005ftoken_005f0);
    return false;
  }
}
